[package]
name = "todo-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
num_cpus = "1.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.44"
serde_derive = "1.0.104"
aws-config = "0.49.0"
aws-sdk-dynamodb = "0.19.0"
tokio-stream = "0.1.10"

[dev-dependencies]
bytes="0.5.3"

[features]
dynamo = []